### ISSUE TITLE
Barotropic run setup

### ISSUE THREAD

**Issue by seshrajagopal** [CADWRDeltaModeling/BayDeltaSCHISM#35] opened 2023-06-20 15:18 UTC
1. How do you check that prepare_schism finished successfully? Presently we rely on the message "done" at the end of the process and check if the gr3 files were created. 
2. How do you check elev2D.bat was successful? Currently you check that the elev2D.*.th.nc is created, is there any other way to check?
3. multi_clip uses a DCD sink source file, it is unclear how that sink file is created.

**Comment by water-e** [comment] 2023-07-22 07:24
Shey I'm closing this because the ideas are too broad to be a single issue in issue tracking. I have created issue #38 to convey that we would like to address regression testing items. 

If you see "Done" there probably was no error with prepare_schism. Similarly you should see elev2D bomb. prepare_schism does about 20 things, so hard to be specific. For elev2D the things that can go wrong is that NOAA delivers an unexpected datum (they've gone back and forth between using NAVD88 or NAVD in the URL and it lapses to a station datum if you do it wrong). Or sometimes data at Point Reyes is missing ... you'll get warned about that though.

**Closed** 2024-03-20 13:43 UTC
